spring:
  config:
    activate:
      on-profile: local-security

security:
  jwt:
    token:
      secretKey: asccesssecretkeyoverflowsecrekey
      access:
        validTime: 1800000
      refresh:
        validTime: 3600000