spring:
  config:
    activate:
      on-profile: dev-security

security:
  jwt:
    token:
      secretKey: asccesssecretkeyoverflowsecrekey
      access:
        validTime: 180
      refresh:
        validTime : 360

