spring:
  config:
    activate:
      on-profile: local-security

security:
  jwt:
    token:
      access:
        secretKey: asccesssecretkeyoverflowsecrekey
        validTime: 1800000
      refresh:
        secretKey: refreshsecretkeyoverflowsecrekey
        validTime: 604800000